# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BiteGeoJsonModelProperties")

model_instance <- BiteGeoJsonModelProperties$new()

test_that("received_at", {
  # tests for the property `received_at` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`received_at`, "EXPECTED_RESULT")
})
