# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DeviceRequest")

model_instance <- DeviceRequest$new()

test_that("manufacturer", {
  # tests for the property `manufacturer` (character)
  # Manufacturer of device from which this report was submitted.

  # uncomment below to test the property
  #expect_equal(model.instance$`manufacturer`, "EXPECTED_RESULT")
})

test_that("model", {
  # tests for the property `model` (character)
  # Model of device from which this report was submitted.

  # uncomment below to test the property
  #expect_equal(model.instance$`model`, "EXPECTED_RESULT")
})

test_that("os", {
  # tests for the property `os` (character)
  # Operating system of device from which this report was submitted.

  # uncomment below to test the property
  #expect_equal(model.instance$`os`, "EXPECTED_RESULT")
})

test_that("os_version", {
  # tests for the property `os_version` (character)
  # Operating system version of device from which this report was submitted.

  # uncomment below to test the property
  #expect_equal(model.instance$`os_version`, "EXPECTED_RESULT")
})

test_that("os_language", {
  # tests for the property `os_language` (character)
  # Language setting of operating system on device from which this report was submitted. 2-digit ISO-639-1 language code.

  # uncomment below to test the property
  #expect_equal(model.instance$`os_language`, "EXPECTED_RESULT")
})
