# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LocalizedMessageBodyRequest")

model_instance <- LocalizedMessageBodyRequest$new()

test_that("bg", {
  # tests for the property `bg` (character)
  # Български

  # uncomment below to test the property
  #expect_equal(model.instance$`bg`, "EXPECTED_RESULT")
})

test_that("bn", {
  # tests for the property `bn` (character)
  # বাংলা

  # uncomment below to test the property
  #expect_equal(model.instance$`bn`, "EXPECTED_RESULT")
})

test_that("ca", {
  # tests for the property `ca` (character)
  # Català

  # uncomment below to test the property
  #expect_equal(model.instance$`ca`, "EXPECTED_RESULT")
})

test_that("de", {
  # tests for the property `de` (character)
  # Deutsch

  # uncomment below to test the property
  #expect_equal(model.instance$`de`, "EXPECTED_RESULT")
})

test_that("el", {
  # tests for the property `el` (character)
  # Ελληνικά

  # uncomment below to test the property
  #expect_equal(model.instance$`el`, "EXPECTED_RESULT")
})

test_that("en", {
  # tests for the property `en` (character)
  # English

  # uncomment below to test the property
  #expect_equal(model.instance$`en`, "EXPECTED_RESULT")
})

test_that("es", {
  # tests for the property `es` (character)
  # Español

  # uncomment below to test the property
  #expect_equal(model.instance$`es`, "EXPECTED_RESULT")
})

test_that("eu", {
  # tests for the property `eu` (character)
  # Basque

  # uncomment below to test the property
  #expect_equal(model.instance$`eu`, "EXPECTED_RESULT")
})

test_that("fr", {
  # tests for the property `fr` (character)
  # Français

  # uncomment below to test the property
  #expect_equal(model.instance$`fr`, "EXPECTED_RESULT")
})

test_that("gl", {
  # tests for the property `gl` (character)
  # Galego

  # uncomment below to test the property
  #expect_equal(model.instance$`gl`, "EXPECTED_RESULT")
})

test_that("hr", {
  # tests for the property `hr` (character)
  # Hrvatski

  # uncomment below to test the property
  #expect_equal(model.instance$`hr`, "EXPECTED_RESULT")
})

test_that("hu", {
  # tests for the property `hu` (character)
  # Magyar

  # uncomment below to test the property
  #expect_equal(model.instance$`hu`, "EXPECTED_RESULT")
})

test_that("it", {
  # tests for the property `it` (character)
  # Italiano

  # uncomment below to test the property
  #expect_equal(model.instance$`it`, "EXPECTED_RESULT")
})

test_that("lb", {
  # tests for the property `lb` (character)
  # Lëtzebuergesch

  # uncomment below to test the property
  #expect_equal(model.instance$`lb`, "EXPECTED_RESULT")
})

test_that("mk", {
  # tests for the property `mk` (character)
  # Македонски

  # uncomment below to test the property
  #expect_equal(model.instance$`mk`, "EXPECTED_RESULT")
})

test_that("nl", {
  # tests for the property `nl` (character)
  # Nederlands

  # uncomment below to test the property
  #expect_equal(model.instance$`nl`, "EXPECTED_RESULT")
})

test_that("pt", {
  # tests for the property `pt` (character)
  # Português

  # uncomment below to test the property
  #expect_equal(model.instance$`pt`, "EXPECTED_RESULT")
})

test_that("ro", {
  # tests for the property `ro` (character)
  # Română

  # uncomment below to test the property
  #expect_equal(model.instance$`ro`, "EXPECTED_RESULT")
})

test_that("sl", {
  # tests for the property `sl` (character)
  # Slovenščina

  # uncomment below to test the property
  #expect_equal(model.instance$`sl`, "EXPECTED_RESULT")
})

test_that("sq", {
  # tests for the property `sq` (character)
  # Shqip

  # uncomment below to test the property
  #expect_equal(model.instance$`sq`, "EXPECTED_RESULT")
})

test_that("sr", {
  # tests for the property `sr` (character)
  # Српски

  # uncomment below to test the property
  #expect_equal(model.instance$`sr`, "EXPECTED_RESULT")
})

test_that("sv", {
  # tests for the property `sv` (character)
  # Svenska

  # uncomment below to test the property
  #expect_equal(model.instance$`sv`, "EXPECTED_RESULT")
})

test_that("tr", {
  # tests for the property `tr` (character)
  # Türkçe

  # uncomment below to test the property
  #expect_equal(model.instance$`tr`, "EXPECTED_RESULT")
})

test_that("zh-cn", {
  # tests for the property `zh-cn` (character)
  # 简体中文

  # uncomment below to test the property
  #expect_equal(model.instance$`zh-cn`, "EXPECTED_RESULT")
})
