# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ObservationsApi")

api_instance <- ObservationsApi$new()

test_that("create", {
  # tests for create
  # base path: https://api.mosquitoalert.com/v1
  # @param created_at character 
  # @param sent_at character 
  # @param location LocationRequest 
  # @param photos array[SimplePhotoRequest] 
  # @param note character Note user attached to report. (optional)
  # @param tags array[character]  (optional)
  # @param event_environment character The environment where the event took place. (optional)
  # @param event_moment character The moment of the day when the event took place. (optional)
  # @param mosquito_appearance MosquitoAppearanceRequest User-provided description of the mosquito's appearance (optional)
  # @return [Observation]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("destroy", {
  # tests for destroy
  # base path: https://api.mosquitoalert.com/v1
  # @param uuid character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("list", {
  # tests for list
  # base path: https://api.mosquitoalert.com/v1
  # @param country_id integer  (optional)
  # @param created_at_after character Created at (optional)
  # @param created_at_before character Created at (optional)
  # @param has_photos character Has any photo (optional)
  # @param identification_taxon_ids array[integer]  (optional)
  # @param order_by array[character] Ordenado   (optional)
  # @param page integer A page number within the paginated result set. (optional)
  # @param page_size integer Number of results to return per page. (optional)
  # @param received_at_after character Received at (optional)
  # @param received_at_before character Received at (optional)
  # @param short_id character Short ID (optional)
  # @param updated_at_after character Update at (optional)
  # @param updated_at_before character Update at (optional)
  # @param user_uuid character  (optional)
  # @return [PaginatedObservationList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("list_mine", {
  # tests for list_mine
  # base path: https://api.mosquitoalert.com/v1
  # Get Current User&#39;s Observations
  # @param country_id integer  (optional)
  # @param created_at_after character Created at (optional)
  # @param created_at_before character Created at (optional)
  # @param has_photos character Has any photo (optional)
  # @param identification_taxon_ids array[integer]  (optional)
  # @param order_by array[character] Ordenado   (optional)
  # @param page integer A page number within the paginated result set. (optional)
  # @param page_size integer Number of results to return per page. (optional)
  # @param received_at_after character Received at (optional)
  # @param received_at_before character Received at (optional)
  # @param short_id character Short ID (optional)
  # @param updated_at_after character Update at (optional)
  # @param updated_at_before character Update at (optional)
  # @param user_uuid character  (optional)
  # @return [PaginatedObservationList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("retrieve", {
  # tests for retrieve
  # base path: https://api.mosquitoalert.com/v1
  # @param uuid character 
  # @return [Observation]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
