# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BoundariesApi")

api_instance <- BoundariesApi$new()

test_that("create_temporary", {
  # tests for create_temporary
  # base path: https://api.mosquitoalert.com/v1
  # Create a temporary boundary
  # @param temporary_boundary_request TemporaryBoundaryRequest 
  # @return [TemporaryBoundary]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
