# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Location")

model_instance <- Location$new()

test_that("type", {
  # tests for the property `type` (character)
  # Did user indicate that report relates to current location of phone (&#39;current&#39;) or to a location selected manually on the map (&#39;selected&#39;)? Or is the choice missing (&#39;missing&#39;)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("point", {
  # tests for the property `point` (LocationPoint)

  # uncomment below to test the property
  #expect_equal(model.instance$`point`, "EXPECTED_RESULT")
})

test_that("timezone", {
  # tests for the property `timezone` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`timezone`, "EXPECTED_RESULT")
})

test_that("country_id", {
  # tests for the property `country_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`country_id`, "EXPECTED_RESULT")
})

test_that("nuts_2", {
  # tests for the property `nuts_2` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nuts_2`, "EXPECTED_RESULT")
})

test_that("nuts_3", {
  # tests for the property `nuts_3` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nuts_3`, "EXPECTED_RESULT")
})
