# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DeviceRequest")

model_instance <- DeviceRequest$new()

test_that("device_id", {
  # tests for the property `device_id` (character)
  # Unique device identifier

  # uncomment below to test the property
  #expect_equal(model.instance$`device_id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("fcm_token", {
  # tests for the property `fcm_token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`fcm_token`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("manufacturer", {
  # tests for the property `manufacturer` (character)
  # The manufacturer of the device.

  # uncomment below to test the property
  #expect_equal(model.instance$`manufacturer`, "EXPECTED_RESULT")
})

test_that("model", {
  # tests for the property `model` (character)
  # The end-user-visible name for the end product.

  # uncomment below to test the property
  #expect_equal(model.instance$`model`, "EXPECTED_RESULT")
})

test_that("os", {
  # tests for the property `os` (DeviceOsRequest)

  # uncomment below to test the property
  #expect_equal(model.instance$`os`, "EXPECTED_RESULT")
})

test_that("mobile_app", {
  # tests for the property `mobile_app` (MobileAppRequest)

  # uncomment below to test the property
  #expect_equal(model.instance$`mobile_app`, "EXPECTED_RESULT")
})
