# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserAssignment")

model_instance <- UserAssignment$new()

test_that("user", {
  # tests for the property `user` (SimpleAnnotatorUser)

  # uncomment below to test the property
  #expect_equal(model.instance$`user`, "EXPECTED_RESULT")
})

test_that("annotation_id", {
  # tests for the property `annotation_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`annotation_id`, "EXPECTED_RESULT")
})

test_that("annotation_type", {
  # tests for the property `annotation_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`annotation_type`, "EXPECTED_RESULT")
})
