# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MessageRecipient")

model_instance <- MessageRecipient$new()

test_that("user", {
  # tests for the property `user` (MinimalUser)

  # uncomment below to test the property
  #expect_equal(model.instance$`user`, "EXPECTED_RESULT")
})

test_that("has_read", {
  # tests for the property `has_read` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`has_read`, "EXPECTED_RESULT")
})
