# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AppUserTokenObtainPair")

model_instance <- AppUserTokenObtainPair$new()

test_that("access", {
  # tests for the property `access` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`access`, "EXPECTED_RESULT")
})

test_that("refresh", {
  # tests for the property `refresh` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`refresh`, "EXPECTED_RESULT")
})
