# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateTopicMessageContent")

model_instance <- CreateTopicMessageContent$new()

test_that("title", {
  # tests for the property `title` (LocalizedTopicMessageTitle)
  # Provide the message&#39;s title in all supported languages for this topic

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("body", {
  # tests for the property `body` (LocalizedTopicMessageBody)
  # Provide the message&#39;s body in all supported languages for this topic

  # uncomment below to test the property
  #expect_equal(model.instance$`body`, "EXPECTED_RESULT")
})
