# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test IdentificationTasksApi")

api_instance <- IdentificationTasksApi$new()

test_that("annotations_create", {
  # tests for annotations_create
  # base path: https://api.mosquitoalert.com/v1
  # @param observation_uuid character UUID of the Observation
  # @param annotation_request AnnotationRequest 
  # @return [Annotation]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("annotations_list", {
  # tests for annotations_list
  # base path: https://api.mosquitoalert.com/v1
  # @param observation_uuid character UUID of the Observation
  # @param classification_confidence_label character  (optional)
  # @param classification_confidence_max numeric  (optional)
  # @param classification_confidence_min numeric  (optional)
  # @param classification_taxon_ids array[integer]  (optional)
  # @param created_at_after character Created at (optional)
  # @param created_at_before character Created at (optional)
  # @param is_decisive character  (optional)
  # @param is_flagged character  (optional)
  # @param order_by array[character] Ordenado   (optional)
  # @param page integer A page number within the paginated result set. (optional)
  # @param page_size integer Number of results to return per page. (optional)
  # @param updated_at_after character Updated at (optional)
  # @param updated_at_before character Updated at (optional)
  # @param user_ids array[integer]  (optional)
  # @return [PaginatedAnnotationList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("annotations_list_mine", {
  # tests for annotations_list_mine
  # base path: https://api.mosquitoalert.com/v1
  # Get my annotations
  # @param classification_confidence_label character  (optional)
  # @param classification_confidence_max numeric  (optional)
  # @param classification_confidence_min numeric  (optional)
  # @param classification_taxon_ids array[integer]  (optional)
  # @param created_at_after character Created at (optional)
  # @param created_at_before character Created at (optional)
  # @param is_decisive character  (optional)
  # @param is_flagged character  (optional)
  # @param order_by array[character] Ordenado   (optional)
  # @param page integer A page number within the paginated result set. (optional)
  # @param page_size integer Number of results to return per page. (optional)
  # @param updated_at_after character Updated at (optional)
  # @param updated_at_before character Updated at (optional)
  # @param user_ids array[integer]  (optional)
  # @return [PaginatedAnnotationList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("annotations_retrieve", {
  # tests for annotations_retrieve
  # base path: https://api.mosquitoalert.com/v1
  # @param id integer A unique integer value identifying this expert report annotation.
  # @param observation_uuid character UUID of the Observation
  # @return [Annotation]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("assign_next", {
  # tests for assign_next
  # base path: https://api.mosquitoalert.com/v1
  # Assign the next available identification task.
  # @return [Assignment]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("list", {
  # tests for list
  # base path: https://api.mosquitoalert.com/v1
  # @param annotator_ids array[integer]  (optional)
  # @param assignee_ids array[integer]  (optional)
  # @param created_at_after character Created at (optional)
  # @param created_at_before character Created at (optional)
  # @param fully_predicted character Filters identification task based on whether all associated photos have predictions. Set to True to include identification tasks where every photo has a prediction; set to False to include identification tasks where at least one photo is missing a prediction. (optional)
  # @param is_flagged character  (optional)
  # @param is_safe character  (optional)
  # @param num_annotations_max integer  (optional)
  # @param num_annotations_min integer  (optional)
  # @param observation_country_ids array[integer]  (optional)
  # @param order_by array[character] Ordenado   (optional)
  # @param page integer A page number within the paginated result set. (optional)
  # @param page_size integer Number of results to return per page. (optional)
  # @param result_agreement_max numeric  (optional)
  # @param result_agreement_min numeric  (optional)
  # @param result_confidence_max numeric  (optional)
  # @param result_confidence_min numeric  (optional)
  # @param result_source character  (optional)
  # @param result_taxon_ids array[integer]  (optional)
  # @param result_uncertainty_max numeric  (optional)
  # @param result_uncertainty_min numeric  (optional)
  # @param review_type character  (optional)
  # @param status array[character]  (optional)
  # @param updated_at_after character Update at (optional)
  # @param updated_at_before character Update at (optional)
  # @return [PaginatedIdentificationTaskList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("list_mine", {
  # tests for list_mine
  # base path: https://api.mosquitoalert.com/v1
  # Get identification tasks annotated by me
  # @param annotator_ids array[integer]  (optional)
  # @param assignee_ids array[integer]  (optional)
  # @param created_at_after character Created at (optional)
  # @param created_at_before character Created at (optional)
  # @param fully_predicted character Filters identification task based on whether all associated photos have predictions. Set to True to include identification tasks where every photo has a prediction; set to False to include identification tasks where at least one photo is missing a prediction. (optional)
  # @param is_flagged character  (optional)
  # @param is_safe character  (optional)
  # @param num_annotations_max integer  (optional)
  # @param num_annotations_min integer  (optional)
  # @param observation_country_ids array[integer]  (optional)
  # @param order_by array[character] Ordenado   (optional)
  # @param page integer A page number within the paginated result set. (optional)
  # @param page_size integer Number of results to return per page. (optional)
  # @param result_agreement_max numeric  (optional)
  # @param result_agreement_min numeric  (optional)
  # @param result_confidence_max numeric  (optional)
  # @param result_confidence_min numeric  (optional)
  # @param result_source character  (optional)
  # @param result_taxon_ids array[integer]  (optional)
  # @param result_uncertainty_max numeric  (optional)
  # @param result_uncertainty_min numeric  (optional)
  # @param review_type character  (optional)
  # @param status array[character]  (optional)
  # @param updated_at_after character Update at (optional)
  # @param updated_at_before character Update at (optional)
  # @return [PaginatedIdentificationTaskList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("predictions_create", {
  # tests for predictions_create
  # base path: https://api.mosquitoalert.com/v1
  # @param observation_uuid character UUID of the Observation
  # @param create_photo_prediction_request CreatePhotoPredictionRequest 
  # @return [CreatePhotoPrediction]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("predictions_destroy", {
  # tests for predictions_destroy
  # base path: https://api.mosquitoalert.com/v1
  # @param observation_uuid character UUID of the Observation
  # @param photo_uuid character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("predictions_list", {
  # tests for predictions_list
  # base path: https://api.mosquitoalert.com/v1
  # @param observation_uuid character UUID of the Observation
  # @param page integer A page number within the paginated result set. (optional)
  # @param page_size integer Number of results to return per page. (optional)
  # @return [PaginatedPhotoPredictionList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("predictions_partial_update", {
  # tests for predictions_partial_update
  # base path: https://api.mosquitoalert.com/v1
  # @param observation_uuid character UUID of the Observation
  # @param photo_uuid character 
  # @param patched_photo_prediction_request PatchedPhotoPredictionRequest  (optional)
  # @return [PhotoPrediction]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("predictions_retrieve", {
  # tests for predictions_retrieve
  # base path: https://api.mosquitoalert.com/v1
  # @param observation_uuid character UUID of the Observation
  # @param photo_uuid character 
  # @return [PhotoPrediction]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("predictions_update", {
  # tests for predictions_update
  # base path: https://api.mosquitoalert.com/v1
  # @param observation_uuid character UUID of the Observation
  # @param photo_uuid character 
  # @param photo_prediction_request PhotoPredictionRequest 
  # @return [PhotoPrediction]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("retrieve", {
  # tests for retrieve
  # base path: https://api.mosquitoalert.com/v1
  # @param observation_uuid character 
  # @return [IdentificationTask]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
