# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MessageTopic")

model_instance <- MessageTopic$new()

test_that("code", {
  # tests for the property `code` (character)
  # Code for the topic.

  # uncomment below to test the property
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Description for the topic, in english.

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})
