# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateOverwriteReviewRequest")

model_instance <- CreateOverwriteReviewRequest$new()

test_that("action", {
  # tests for the property `action` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`action`, "EXPECTED_RESULT")
})

test_that("public_photo_uuid", {
  # tests for the property `public_photo_uuid` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`public_photo_uuid`, "EXPECTED_RESULT")
})

test_that("is_safe", {
  # tests for the property `is_safe` (character)
  # Indicates if the content is safe for publication.

  # uncomment below to test the property
  #expect_equal(model.instance$`is_safe`, "EXPECTED_RESULT")
})

test_that("public_note", {
  # tests for the property `public_note` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`public_note`, "EXPECTED_RESULT")
})

test_that("classification", {
  # tests for the property `classification` (SpeciesClassificationRequest)

  # uncomment below to test the property
  #expect_equal(model.instance$`classification`, "EXPECTED_RESULT")
})

test_that("characteristics", {
  # tests for the property `characteristics` (SpeciesCharacteristicsRequest)

  # uncomment below to test the property
  #expect_equal(model.instance$`characteristics`, "EXPECTED_RESULT")
})
