# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TokenRefreshRequest")

model_instance <- TokenRefreshRequest$new()

test_that("refresh", {
  # tests for the property `refresh` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`refresh`, "EXPECTED_RESULT")
})
