# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Photo")

model_instance <- Photo$new()

test_that("uuid", {
  # tests for the property `uuid` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("image_url", {
  # tests for the property `image_url` (character)
  # Photo uploaded by user.

  # uncomment below to test the property
  #expect_equal(model.instance$`image_url`, "EXPECTED_RESULT")
})

test_that("image_path", {
  # tests for the property `image_path` (character)
  # Internal server path of the image.

  # uncomment below to test the property
  #expect_equal(model.instance$`image_path`, "EXPECTED_RESULT")
})
