# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserScore")

model_instance <- UserScore$new()

test_that("value", {
  # tests for the property `value` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("updated_at", {
  # tests for the property `updated_at` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`updated_at`, "EXPECTED_RESULT")
})
