# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AnnotationCharacteristics")

model_instance <- AnnotationCharacteristics$new()

test_that("sex", {
  # tests for the property `sex` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sex`, "EXPECTED_RESULT")
})

test_that("is_blood_fed", {
  # tests for the property `is_blood_fed` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_blood_fed`, "EXPECTED_RESULT")
})

test_that("is_gravid", {
  # tests for the property `is_gravid` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_gravid`, "EXPECTED_RESULT")
})
