# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AdmBoundaryRequest")

model_instance <- AdmBoundaryRequest$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("code", {
  # tests for the property `code` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("source", {
  # tests for the property `source` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`source`, "EXPECTED_RESULT")
})

test_that("level", {
  # tests for the property `level` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`level`, "EXPECTED_RESULT")
})
