# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BreedingSitesApi")

api_instance <- BreedingSitesApi$new()

test_that("create", {
  # tests for create
  # base path: https://api.mosquitoalert.com/v1
  # @param created_at character 
  # @param sent_at character 
  # @param location LocationRequest 
  # @param photos array[data.frame] 
  # @param site_type character 
  # @param note character  (optional)
  # @param tags array[character]  (optional)
  # @param has_water character Either if the user perceived water in the breeding site. (optional)
  # @param in_public_area character Either if the breeding site is found in a public area. (optional)
  # @param has_near_mosquitoes character Either if the user perceived mosquitoes near the breeding site (less than 10 meters). (optional)
  # @param has_larvae character Either if the user perceived larvaes the breeding site. (optional)
  # @return [BreedingSite]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("destroy", {
  # tests for destroy
  # base path: https://api.mosquitoalert.com/v1
  # @param uuid character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("geo_list", {
  # tests for geo_list
  # base path: https://api.mosquitoalert.com/v1
  # @param boundary_uuid character  (optional)
  # @param country_id integer  (optional)
  # @param created_at_after character Created at (optional)
  # @param created_at_before character Created at (optional)
  # @param dist numeric Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed. (optional)
  # @param format character  (optional)
  # @param geo_precision numeric Latitude/Longitude precision (optional)
  # @param has_larvae character  (optional)
  # @param has_near_mosquitoes character  (optional)
  # @param has_photos character Has any photo (optional)
  # @param has_water character  (optional)
  # @param order_by array[character] Ordenamiento   (optional)
  # @param point array[numeric] Point represented in **x,y** format. Represents **point** in **Distance to point filter** (optional)
  # @param received_at_after character Received at (optional)
  # @param received_at_before character Received at (optional)
  # @param search character Un término de búsqueda. (optional)
  # @param short_id character Short ID (optional)
  # @param site_type array[character] Breeding site type.   (optional)
  # @param tags array[character] Múltiples valores separados por comas. (optional)
  # @param updated_at_after character Update at (optional)
  # @param updated_at_before character Update at (optional)
  # @param user_uuid character  (optional)
  # @return [array[BreedingSiteGeoModel]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("list", {
  # tests for list
  # base path: https://api.mosquitoalert.com/v1
  # @param boundary_uuid character  (optional)
  # @param country_id integer  (optional)
  # @param created_at_after character Created at (optional)
  # @param created_at_before character Created at (optional)
  # @param dist numeric Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed. (optional)
  # @param format character  (optional)
  # @param geo_precision numeric Latitude/Longitude precision (optional)
  # @param has_larvae character  (optional)
  # @param has_near_mosquitoes character  (optional)
  # @param has_photos character Has any photo (optional)
  # @param has_water character  (optional)
  # @param order_by array[character] Ordenamiento   (optional)
  # @param page integer Un número de página dentro del conjunto de resultados paginado. (optional)
  # @param page_size integer Número de resultados a devolver por página. (optional)
  # @param point array[numeric] Point represented in **x,y** format. Represents **point** in **Distance to point filter** (optional)
  # @param received_at_after character Received at (optional)
  # @param received_at_before character Received at (optional)
  # @param search character Un término de búsqueda. (optional)
  # @param short_id character Short ID (optional)
  # @param site_type array[character] Breeding site type.   (optional)
  # @param tags array[character] Múltiples valores separados por comas. (optional)
  # @param updated_at_after character Update at (optional)
  # @param updated_at_before character Update at (optional)
  # @param user_uuid character  (optional)
  # @return [PaginatedBreedingSiteList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("list_mine", {
  # tests for list_mine
  # base path: https://api.mosquitoalert.com/v1
  # Get Current User&#39;s Breeding Sites
  # @param boundary_uuid character  (optional)
  # @param country_id integer  (optional)
  # @param created_at_after character Created at (optional)
  # @param created_at_before character Created at (optional)
  # @param dist numeric Represents **Distance** in **Distance to point** filter. Default value is used only if ***point*** is passed. (optional)
  # @param format character  (optional)
  # @param geo_precision numeric Latitude/Longitude precision (optional)
  # @param has_larvae character  (optional)
  # @param has_near_mosquitoes character  (optional)
  # @param has_photos character Has any photo (optional)
  # @param has_water character  (optional)
  # @param order_by array[character] Ordenamiento   (optional)
  # @param page integer Un número de página dentro del conjunto de resultados paginado. (optional)
  # @param page_size integer Número de resultados a devolver por página. (optional)
  # @param point array[numeric] Point represented in **x,y** format. Represents **point** in **Distance to point filter** (optional)
  # @param received_at_after character Received at (optional)
  # @param received_at_before character Received at (optional)
  # @param search character Un término de búsqueda. (optional)
  # @param short_id character Short ID (optional)
  # @param site_type array[character] Breeding site type.   (optional)
  # @param tags array[character] Múltiples valores separados por comas. (optional)
  # @param updated_at_after character Update at (optional)
  # @param updated_at_before character Update at (optional)
  # @param user_uuid character  (optional)
  # @return [PaginatedBreedingSiteList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("retrieve", {
  # tests for retrieve
  # base path: https://api.mosquitoalert.com/v1
  # @param uuid character 
  # @return [BreedingSite]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
