# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Country")

model_instance <- Country$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name_en", {
  # tests for the property `name_en` (character)
  # Full name of the country in English (e.g., Spain).

  # uncomment below to test the property
  #expect_equal(model.instance$`name_en`, "EXPECTED_RESULT")
})

test_that("iso3_code", {
  # tests for the property `iso3_code` (character)
  # ISO 3166-1 alpha-3 country code (3-letter code, e.g., ESP).

  # uncomment below to test the property
  #expect_equal(model.instance$`iso3_code`, "EXPECTED_RESULT")
})
