# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BiteCounts")

model_instance <- BiteCounts$new()

test_that("total", {
  # tests for the property `total` (integer)
  # Total number of bites reported.

  # uncomment below to test the property
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

test_that("head", {
  # tests for the property `head` (integer)
  # Number of bites reported in the head.

  # uncomment below to test the property
  #expect_equal(model.instance$`head`, "EXPECTED_RESULT")
})

test_that("left_arm", {
  # tests for the property `left_arm` (integer)
  # Number of bites reported in the left arm.

  # uncomment below to test the property
  #expect_equal(model.instance$`left_arm`, "EXPECTED_RESULT")
})

test_that("right_arm", {
  # tests for the property `right_arm` (integer)
  # Number of bites reported in the right arm.

  # uncomment below to test the property
  #expect_equal(model.instance$`right_arm`, "EXPECTED_RESULT")
})

test_that("chest", {
  # tests for the property `chest` (integer)
  # Number of bites reported in the chest.

  # uncomment below to test the property
  #expect_equal(model.instance$`chest`, "EXPECTED_RESULT")
})

test_that("left_leg", {
  # tests for the property `left_leg` (integer)
  # Number of bites reported in the left leg.

  # uncomment below to test the property
  #expect_equal(model.instance$`left_leg`, "EXPECTED_RESULT")
})

test_that("right_leg", {
  # tests for the property `right_leg` (integer)
  # Number of bites reported in the right leg.

  # uncomment below to test the property
  #expect_equal(model.instance$`right_leg`, "EXPECTED_RESULT")
})
