# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Partner")

model_instance <- Partner$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("point", {
  # tests for the property `point` (PartnerPoint)

  # uncomment below to test the property
  #expect_equal(model.instance$`point`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Text desription on the pin. This text is meant to be visualized as the text body of the dialog on the map

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)
  # URL link to the organization page

  # uncomment below to test the property
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})
