# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateUserRequest")

model_instance <- CreateUserRequest$new()

test_that("device_token", {
  # tests for the property `device_token` (character)
  # Device token, used in messaging. Must be supplied by the client

  # uncomment below to test the property
  #expect_equal(model.instance$`device_token`, "EXPECTED_RESULT")
})

test_that("password", {
  # tests for the property `password` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`password`, "EXPECTED_RESULT")
})
