# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MobileApp")

model_instance <- MobileApp$new()

test_that("package_name", {
  # tests for the property `package_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`package_name`, "EXPECTED_RESULT")
})

test_that("package_version", {
  # tests for the property `package_version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`package_version`, "EXPECTED_RESULT")
})
