# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FixesApi")

api_instance <- FixesApi$new()

test_that("fixes_create", {
  # tests for fixes_create
  # base path: https://api.mosquitoalert.com/v1
  # @param fix_request FixRequest 
  # @return [Fix]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
