# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AuthApi")

api_instance <- AuthApi$new()

test_that("change_password", {
  # tests for change_password
  # base path: https://api.mosquitoalert.com/v1
  # @param password_change_request PasswordChangeRequest 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("obtain_token", {
  # tests for obtain_token
  # base path: https://api.mosquitoalert.com/v1
  # Takes a set of user credentials and returns an access and refresh JSON web token pair to prove the authentication of those credentials.
  # @param app_user_token_obtain_pair_request AppUserTokenObtainPairRequest 
  # @return [AppUserTokenObtainPair]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("refresh_token", {
  # tests for refresh_token
  # base path: https://api.mosquitoalert.com/v1
  # Takes a refresh type JSON web token and returns an access type JSON web token if the refresh token is valid.
  # @param token_refresh_request TokenRefreshRequest 
  # @return [TokenRefresh]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("signup_guest", {
  # tests for signup_guest
  # base path: https://api.mosquitoalert.com/v1
  # @param guest_registration_request GuestRegistrationRequest 
  # @return [GuestRegistration]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("verify_token", {
  # tests for verify_token
  # base path: https://api.mosquitoalert.com/v1
  # Takes a token and indicates if it is valid.  This view provides no information about a token&#39;s fitness for a particular use.
  # @param token_verify_request TokenVerifyRequest 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
