# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MessageTargeting")

model_instance <- MessageTargeting$new()

test_that("target", {
  # tests for the property `target` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`target`, "EXPECTED_RESULT")
})

test_that("audience", {
  # tests for the property `audience` (AudienceFilter)

  # uncomment below to test the property
  #expect_equal(model.instance$`audience`, "EXPECTED_RESULT")
})
