# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AnnotationPermission")

model_instance <- AnnotationPermission$new()

test_that("add", {
  # tests for the property `add` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`add`, "EXPECTED_RESULT")
})

test_that("change", {
  # tests for the property `change` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`change`, "EXPECTED_RESULT")
})

test_that("view", {
  # tests for the property `view` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`view`, "EXPECTED_RESULT")
})

test_that("delete", {
  # tests for the property `delete` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`delete`, "EXPECTED_RESULT")
})

test_that("mark_as_decisive", {
  # tests for the property `mark_as_decisive` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`mark_as_decisive`, "EXPECTED_RESULT")
})
