# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TokenRefresh")

model_instance <- TokenRefresh$new()

test_that("access", {
  # tests for the property `access` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`access`, "EXPECTED_RESULT")
})
