# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BiteGeoJsonModelList")

model_instance <- BiteGeoJsonModelList$new()

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("features", {
  # tests for the property `features` (array[BiteGeoJsonModel])

  # uncomment below to test the property
  #expect_equal(model.instance$`features`, "EXPECTED_RESULT")
})
