# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Assignment")

model_instance <- Assignment$new()

test_that("observation", {
  # tests for the property `observation` (AssignedObservation)

  # uncomment below to test the property
  #expect_equal(model.instance$`observation`, "EXPECTED_RESULT")
})

test_that("annotation_type", {
  # tests for the property `annotation_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`annotation_type`, "EXPECTED_RESULT")
})
