# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SimplifiedObservationWithPhotos")

model_instance <- SimplifiedObservationWithPhotos$new()

test_that("uuid", {
  # tests for the property `uuid` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("user_uuid", {
  # tests for the property `user_uuid` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`user_uuid`, "EXPECTED_RESULT")
})

test_that("created_at", {
  # tests for the property `created_at` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})

test_that("created_at_local", {
  # tests for the property `created_at_local` (character)
  # The date and time when the record was created, displayed in the local timezone specified for this entry.

  # uncomment below to test the property
  #expect_equal(model.instance$`created_at_local`, "EXPECTED_RESULT")
})

test_that("received_at", {
  # tests for the property `received_at` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`received_at`, "EXPECTED_RESULT")
})

test_that("location", {
  # tests for the property `location` (SimplifiedLocation)

  # uncomment below to test the property
  #expect_equal(model.instance$`location`, "EXPECTED_RESULT")
})

test_that("note", {
  # tests for the property `note` (character)
  # Note user attached to report.

  # uncomment below to test the property
  #expect_equal(model.instance$`note`, "EXPECTED_RESULT")
})

test_that("photos", {
  # tests for the property `photos` (array[SimplePhoto])

  # uncomment below to test the property
  #expect_equal(model.instance$`photos`, "EXPECTED_RESULT")
})
