# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Identification")

model_instance <- Identification$new()

test_that("photo", {
  # tests for the property `photo` (SimplePhoto)

  # uncomment below to test the property
  #expect_equal(model.instance$`photo`, "EXPECTED_RESULT")
})

test_that("num_annotations", {
  # tests for the property `num_annotations` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`num_annotations`, "EXPECTED_RESULT")
})

test_that("result", {
  # tests for the property `result` (IdentificationTaskResult)

  # uncomment below to test the property
  #expect_equal(model.instance$`result`, "EXPECTED_RESULT")
})

test_that("public_note", {
  # tests for the property `public_note` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`public_note`, "EXPECTED_RESULT")
})
