# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StatusApi")

api_instance <- StatusApi$new()

test_that("retrieve", {
  # tests for retrieve
  # base path: https://api.mosquitoalert.com/v1
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
