# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ReportStatsRow")

model_instance <- ReportStatsRow$new()

test_that("date", {
  # tests for the property `date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`date`, "EXPECTED_RESULT")
})

test_that("region_id", {
  # tests for the property `region_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`region_id`, "EXPECTED_RESULT")
})

test_that("region_code", {
  # tests for the property `region_code` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`region_code`, "EXPECTED_RESULT")
})

test_that("region_name", {
  # tests for the property `region_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`region_name`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("count", {
  # tests for the property `count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`count`, "EXPECTED_RESULT")
})
