# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TaxaListValidationError")

model_instance <- TaxaListValidationError$new()

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("errors", {
  # tests for the property `errors` (array[TaxaListError])

  # uncomment below to test the property
  #expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})
