# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateAudienceMessageRequest")

model_instance <- CreateAudienceMessageRequest$new()

test_that("content", {
  # tests for the property `content` (CreateAudienceMessageContentRequest)
  # The content of the message for the audience

  # uncomment below to test the property
  #expect_equal(model.instance$`content`, "EXPECTED_RESULT")
})

test_that("target", {
  # tests for the property `target` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`target`, "EXPECTED_RESULT")
})

test_that("audience", {
  # tests for the property `audience` (AudienceFilterRequest)
  # The audience filter for the message

  # uncomment below to test the property
  #expect_equal(model.instance$`audience`, "EXPECTED_RESULT")
})
