# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ObservationGeoJsonModelProperties")

model_instance <- ObservationGeoJsonModelProperties$new()

test_that("uuid", {
  # tests for the property `uuid` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("received_at", {
  # tests for the property `received_at` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`received_at`, "EXPECTED_RESULT")
})

test_that("identification_taxon_id", {
  # tests for the property `identification_taxon_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`identification_taxon_id`, "EXPECTED_RESULT")
})
