# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SimplePhoto")

model_instance <- SimplePhoto$new()

test_that("uuid", {
  # tests for the property `uuid` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)
  # URL of the photo associated with the item. Note: This URL may change over time. Do not rely on it for permanent storage.

  # uncomment below to test the property
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})
