# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SimplePhotoRequest")

model_instance <- SimplePhotoRequest$new()

test_that("file", {
  # tests for the property `file` (data.frame)

  # uncomment below to test the property
  #expect_equal(model.instance$`file`, "EXPECTED_RESULT")
})
