# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AdmBoundariesRequest")

model_instance <- AdmBoundariesRequest$new()

test_that("nuts", {
  # tests for the property `nuts` (NutsAdmBoundariesRequest)
  # NUTS (Nomenclature of Territorial Units for Statistics). A hierarchical system used by the European Union to divide its territory into comparable regions for statistical purposes.

  # uncomment below to test the property
  #expect_equal(model.instance$`nuts`, "EXPECTED_RESULT")
})
