# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateUser")

model_instance <- CreateUser$new()

test_that("uuid", {
  # tests for the property `uuid` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`uuid`, "EXPECTED_RESULT")
})

test_that("registration_time", {
  # tests for the property `registration_time` (character)
  # The date and time when user registered and consented to sharing data. Automatically set by server when user uploads registration.

  # uncomment below to test the property
  #expect_equal(model.instance$`registration_time`, "EXPECTED_RESULT")
})

test_that("score", {
  # tests for the property `score` (integer)
  # Global XP Score. This field is updated whenever the user asks for the score, and is only stored here. The content must equal score_v2_adult + score_v2_bite + score_v2_site

  # uncomment below to test the property
  #expect_equal(model.instance$`score`, "EXPECTED_RESULT")
})

test_that("last_score_update", {
  # tests for the property `last_score_update` (character)
  # Last time score was updated

  # uncomment below to test the property
  #expect_equal(model.instance$`last_score_update`, "EXPECTED_RESULT")
})
