# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Campaign")

model_instance <- Campaign$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("country_id", {
  # tests for the property `country_id` (integer)
  # Country in which the campaign is taking place

  # uncomment below to test the property
  #expect_equal(model.instance$`country_id`, "EXPECTED_RESULT")
})

test_that("posting_address", {
  # tests for the property `posting_address` (character)
  # Full posting address of the place where the samples will be sent

  # uncomment below to test the property
  #expect_equal(model.instance$`posting_address`, "EXPECTED_RESULT")
})

test_that("start_date", {
  # tests for the property `start_date` (character)
  # Date when the campaign starts. No samples should be collected BEFORE this date.

  # uncomment below to test the property
  #expect_equal(model.instance$`start_date`, "EXPECTED_RESULT")
})

test_that("end_date", {
  # tests for the property `end_date` (character)
  # Date when the campaign ends. No samples should be collected AFTER this date.

  # uncomment below to test the property
  #expect_equal(model.instance$`end_date`, "EXPECTED_RESULT")
})
