# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AnnotationRequest")

model_instance <- AnnotationRequest$new()

test_that("best_photo_uuid", {
  # tests for the property `best_photo_uuid` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`best_photo_uuid`, "EXPECTED_RESULT")
})

test_that("classification", {
  # tests for the property `classification` (AnnotationClassificationRequest)

  # uncomment below to test the property
  #expect_equal(model.instance$`classification`, "EXPECTED_RESULT")
})

test_that("feedback", {
  # tests for the property `feedback` (AnnotationFeedbackRequest)

  # uncomment below to test the property
  #expect_equal(model.instance$`feedback`, "EXPECTED_RESULT")
})

test_that("is_flagged", {
  # tests for the property `is_flagged` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_flagged`, "EXPECTED_RESULT")
})

test_that("is_decisive", {
  # tests for the property `is_decisive` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_decisive`, "EXPECTED_RESULT")
})

test_that("tags", {
  # tests for the property `tags` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`tags`, "EXPECTED_RESULT")
})
