# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BreedingSiteGeoJsonModelProperties")

model_instance <- BreedingSiteGeoJsonModelProperties$new()

test_that("received_at", {
  # tests for the property `received_at` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`received_at`, "EXPECTED_RESULT")
})

test_that("site_type", {
  # tests for the property `site_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`site_type`, "EXPECTED_RESULT")
})

test_that("has_water", {
  # tests for the property `has_water` (character)
  # Either if the user perceived water in the breeding site.

  # uncomment below to test the property
  #expect_equal(model.instance$`has_water`, "EXPECTED_RESULT")
})
