# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DevicesApi")

api_instance <- DevicesApi$new()

test_that("create", {
  # tests for create
  # base path: https://api.mosquitoalert.com/v1
  # @param device_request DeviceRequest 
  # @return [Device]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("partial_update", {
  # tests for partial_update
  # base path: https://api.mosquitoalert.com/v1
  # @param device_id character 
  # @param patched_device_update_request PatchedDeviceUpdateRequest  (optional)
  # @return [DeviceUpdate]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("retrieve", {
  # tests for retrieve
  # base path: https://api.mosquitoalert.com/v1
  # @param device_id character 
  # @return [Device]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("update", {
  # tests for update
  # base path: https://api.mosquitoalert.com/v1
  # @param device_id character 
  # @param device_update_request DeviceUpdateRequest 
  # @return [DeviceUpdate]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
