# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SimpleTaxon")

model_instance <- SimpleTaxon$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("common_name", {
  # tests for the property `common_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`common_name`, "EXPECTED_RESULT")
})

test_that("rank", {
  # tests for the property `rank` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`rank`, "EXPECTED_RESULT")
})

test_that("italicize", {
  # tests for the property `italicize` (character)
  # Display the name in italics when rendering.

  # uncomment below to test the property
  #expect_equal(model.instance$`italicize`, "EXPECTED_RESULT")
})
