# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TopicNotificationCreateRequest")

model_instance <- TopicNotificationCreateRequest$new()

test_that("receiver_type", {
  # tests for the property `receiver_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`receiver_type`, "EXPECTED_RESULT")
})

test_that("title_en", {
  # tests for the property `title_en` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`title_en`, "EXPECTED_RESULT")
})

test_that("body_en", {
  # tests for the property `body_en` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`body_en`, "EXPECTED_RESULT")
})

test_that("topic_code", {
  # tests for the property `topic_code` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`topic_code`, "EXPECTED_RESULT")
})
