# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StatsApi")

api_instance <- StatsApi$new()

test_that("list", {
  # tests for list
  # base path: https://api.mosquitoalert.com/v1
  # Aggregated report counts (for displaying data tables or charts, for example). The keys present on each row of &#x60;data&#x60; depend on &#x60;group_by&#x60; (always includes &#x60;count&#x60;, plus &#x60;date&#x60; if grouped by date, &#x60;region_id&#x60;/&#x60;region_code&#x60;/&#x60;region_name&#x60; if grouped by region, and &#x60;type&#x60; if grouped by type).
  # @param area character \"\\<level\\>:\\<id\\>\", e.g. \"country:ES\" or \"nuts2:34\". (optional)
  # @param cumulative character Whether to return cumulative counts over time. It only applies when grouping by date. Defaults to False. (optional)
  # @param date_from character  (optional)
  # @param date_to character  (optional)
  # @param group_by array[character] Comma-separated subset of: date, type, region. (optional)
  # @param interval character The interval at which to aggregate data when grouping by date. Defaults to week. (optional)
  # @param level integer The NUTS level to aggregate by when grouping by region. Defaults to NUTS 2. (optional)
  # @param page integer A page number within the paginated result set. (optional)
  # @param page_size integer Number of results to return per page. (optional)
  # @param type array[character] Comma-separated subset of: bite, adult, site. (optional)
  # @return [PaginatedReportStatsResponseList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
