# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CountryPermission")

model_instance <- CountryPermission$new()

test_that("role", {
  # tests for the property `role` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`role`, "EXPECTED_RESULT")
})

test_that("permissions", {
  # tests for the property `permissions` (Permissions)

  # uncomment below to test the property
  #expect_equal(model.instance$`permissions`, "EXPECTED_RESULT")
})

test_that("country", {
  # tests for the property `country` (Country)

  # uncomment below to test the property
  #expect_equal(model.instance$`country`, "EXPECTED_RESULT")
})
