# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateUserMessageRequest")

model_instance <- CreateUserMessageRequest$new()

test_that("user_uuids", {
  # tests for the property `user_uuids` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`user_uuids`, "EXPECTED_RESULT")
})

test_that("content", {
  # tests for the property `content` (MessageContentRequest)
  # The content of the message

  # uncomment below to test the property
  #expect_equal(model.instance$`content`, "EXPECTED_RESULT")
})
