# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BoundingBoxRequest")

model_instance <- BoundingBoxRequest$new()

test_that("x_min", {
  # tests for the property `x_min` (integer)
  # photo bounding box coordinates top left x

  # uncomment below to test the property
  #expect_equal(model.instance$`x_min`, "EXPECTED_RESULT")
})

test_that("y_min", {
  # tests for the property `y_min` (integer)
  # photo bounding box coordinates top left y

  # uncomment below to test the property
  #expect_equal(model.instance$`y_min`, "EXPECTED_RESULT")
})

test_that("x_max", {
  # tests for the property `x_max` (integer)
  # photo bounding box coordinates bottom right x

  # uncomment below to test the property
  #expect_equal(model.instance$`x_max`, "EXPECTED_RESULT")
})

test_that("y_max", {
  # tests for the property `y_max` (integer)
  # photo bounding box coordinates bottom right y

  # uncomment below to test the property
  #expect_equal(model.instance$`y_max`, "EXPECTED_RESULT")
})
