# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CampaignsApi")

api_instance <- CampaignsApi$new()

test_that("list", {
  # tests for list
  # base path: https://api.mosquitoalert.com/v1
  # @param country_id integer Country in which the campaign is taking place (optional)
  # @param is_active character  (optional)
  # @param order_by array[character] Ordenamiento   (optional)
  # @param page integer Un número de página dentro del conjunto de resultados paginado. (optional)
  # @param page_size integer Número de resultados a devolver por página. (optional)
  # @return [PaginatedCampaignList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("retrieve", {
  # tests for retrieve
  # base path: https://api.mosquitoalert.com/v1
  # @param id integer Un valor de entero único que identifique este ow campaigns.
  # @return [Campaign]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
