# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AnnotationClassificationRequest")

model_instance <- AnnotationClassificationRequest$new()

test_that("taxon_id", {
  # tests for the property `taxon_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon_id`, "EXPECTED_RESULT")
})

test_that("confidence_label", {
  # tests for the property `confidence_label` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`confidence_label`, "EXPECTED_RESULT")
})
