# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PartnersApi")

api_instance <- PartnersApi$new()

test_that("partners_list", {
  # tests for partners_list
  # base path: https://api.mosquitoalert.com/v1
  # @param page integer A page number within the paginated result set. (optional)
  # @param page_size integer Number of results to return per page. (optional)
  # @return [PaginatedPartnerList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("partners_retrieve", {
  # tests for partners_retrieve
  # base path: https://api.mosquitoalert.com/v1
  # @param id integer A unique integer value identifying this organization pin.
  # @return [Partner]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
