# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MosquitoAppearance")

model_instance <- MosquitoAppearance$new()

test_that("specie", {
  # tests for the property `specie` (character)
  # The mosquito specie perceived by the user.

  # uncomment below to test the property
  #expect_equal(model.instance$`specie`, "EXPECTED_RESULT")
})

test_that("thorax", {
  # tests for the property `thorax` (character)
  # The species of mosquito that the thorax resembles, according to the user.

  # uncomment below to test the property
  #expect_equal(model.instance$`thorax`, "EXPECTED_RESULT")
})

test_that("abdomen", {
  # tests for the property `abdomen` (character)
  # The species of mosquito that the abdomen resembles, according to the user.

  # uncomment below to test the property
  #expect_equal(model.instance$`abdomen`, "EXPECTED_RESULT")
})

test_that("legs", {
  # tests for the property `legs` (character)
  # The species of mosquito that the leg resembles, according to the user.

  # uncomment below to test the property
  #expect_equal(model.instance$`legs`, "EXPECTED_RESULT")
})
