# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NotificationsApi")

api_instance <- NotificationsApi$new()

test_that("notifications_create", {
  # tests for notifications_create
  # base path: https://api.mosquitoalert.com/v1
  # @param meta_notification_request MetaNotificationRequest  (optional)
  # @return [array[CreateNotification]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("notifications_list", {
  # tests for notifications_list
  # base path: https://api.mosquitoalert.com/v1
  # @param is_read character  (optional)
  # @param order_by array[character] Ordenado   (optional)
  # @param page integer A page number within the paginated result set. (optional)
  # @param page_size integer Number of results to return per page. (optional)
  # @return [PaginatedNotificationList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("notifications_partial_update", {
  # tests for notifications_partial_update
  # base path: https://api.mosquitoalert.com/v1
  # @param id integer A unique integer value identifying this notification.
  # @param patched_notification_request PatchedNotificationRequest  (optional)
  # @return [Notification]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("notifications_retrieve", {
  # tests for notifications_retrieve
  # base path: https://api.mosquitoalert.com/v1
  # @param id integer A unique integer value identifying this notification.
  # @return [Notification]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("notifications_update", {
  # tests for notifications_update
  # base path: https://api.mosquitoalert.com/v1
  # @param id integer A unique integer value identifying this notification.
  # @param notification_request NotificationRequest 
  # @return [Notification]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
