# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Location")

model_instance <- Location$new()

test_that("source", {
  # tests for the property `source` (character)
  # Indicates how the location was obtained. Use &#39;Auto (GPS)&#39; if the location was automatically retrieved from the device&#39;s GPS, or &#39;Manual (User-selected)&#39; if the location was selected by the user on a map.

  # uncomment below to test the property
  #expect_equal(model.instance$`source`, "EXPECTED_RESULT")
})

test_that("point", {
  # tests for the property `point` (Point)

  # uncomment below to test the property
  #expect_equal(model.instance$`point`, "EXPECTED_RESULT")
})

test_that("timezone", {
  # tests for the property `timezone` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`timezone`, "EXPECTED_RESULT")
})

test_that("display_name", {
  # tests for the property `display_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`display_name`, "EXPECTED_RESULT")
})

test_that("country", {
  # tests for the property `country` (Country)

  # uncomment below to test the property
  #expect_equal(model.instance$`country`, "EXPECTED_RESULT")
})

test_that("adm_boundaries", {
  # tests for the property `adm_boundaries` (array[AdmBoundary])

  # uncomment below to test the property
  #expect_equal(model.instance$`adm_boundaries`, "EXPECTED_RESULT")
})
