# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AreaMeta")

model_instance <- AreaMeta$new()

test_that("level", {
  # tests for the property `level` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`level`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("code", {
  # tests for the property `code` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})
