# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NotificationsApi")

api_instance <- NotificationsApi$new()

test_that("create", {
  # tests for create
  # base path: https://api.mosquitoalert.com/v1
  # @param meta_notification_request MetaNotificationRequest  (optional)
  # @return [array[CreateNotification]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("list", {
  # tests for list
  # base path: https://api.mosquitoalert.com/v1
  # @param is_read character  (optional)
  # @param order_by array[character] Ordenado   (optional)
  # @param page integer A page number within the paginated result set. (optional)
  # @param page_size integer Number of results to return per page. (optional)
  # @return [PaginatedNotificationList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("list_mine", {
  # tests for list_mine
  # base path: https://api.mosquitoalert.com/v1
  # Get Current User&#39;s Notifications
  # @param is_read character  (optional)
  # @param order_by array[character] Ordenado   (optional)
  # @param page integer A page number within the paginated result set. (optional)
  # @param page_size integer Number of results to return per page. (optional)
  # @return [PaginatedNotificationList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("partial_update", {
  # tests for partial_update
  # base path: https://api.mosquitoalert.com/v1
  # @param id integer A unique integer value identifying this notification.
  # @param patched_notification_request PatchedNotificationRequest  (optional)
  # @return [Notification]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("retrieve", {
  # tests for retrieve
  # base path: https://api.mosquitoalert.com/v1
  # @param id integer A unique integer value identifying this notification.
  # @return [Notification]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("update", {
  # tests for update
  # base path: https://api.mosquitoalert.com/v1
  # @param id integer A unique integer value identifying this notification.
  # @param notification_request NotificationRequest 
  # @return [Notification]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
