# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateTopicMessageRequest")

model_instance <- CreateTopicMessageRequest$new()

test_that("content", {
  # tests for the property `content` (CreateTopicMessageContentRequest)
  # The content of the message for the topic

  # uncomment below to test the property
  #expect_equal(model.instance$`content`, "EXPECTED_RESULT")
})
