# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UsersApi")

api_instance <- UsersApi$new()

test_that("partial_update", {
  # tests for partial_update
  # base path: https://api.mosquitoalert.com/v1
  # @param uuid character 
  # @param patched_user_request PatchedUserRequest  (optional)
  # @return [User]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("retrieve", {
  # tests for retrieve
  # base path: https://api.mosquitoalert.com/v1
  # @param uuid character 
  # @return [User]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("retrieve_mine", {
  # tests for retrieve_mine
  # base path: https://api.mosquitoalert.com/v1
  # Get Current User&#39;s Profile
  # @return [User]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("update", {
  # tests for update
  # base path: https://api.mosquitoalert.com/v1
  # @param uuid character 
  # @param user_request UserRequest  (optional)
  # @return [User]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
