# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MessageRecipientStats")

model_instance <- MessageRecipientStats$new()

test_that("total", {
  # tests for the property `total` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

test_that("read", {
  # tests for the property `read` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`read`, "EXPECTED_RESULT")
})

test_that("unread", {
  # tests for the property `unread` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`unread`, "EXPECTED_RESULT")
})
