# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NotificationMessage")

model_instance <- NotificationMessage$new()

test_that("title", {
  # tests for the property `title` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("body", {
  # tests for the property `body` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`body`, "EXPECTED_RESULT")
})
