#' Mosquito Alert API
#'
#' Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
#'
#' The version of the OpenAPI document: v1
#' Contact: it@mosquitoalert.com
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Campaigns operations
#' @description CampaignsApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  list  ####################
#'
#' library(MosquitoAlert)
#' var_country_id <- 56 # integer | Country in which the campaign is taking place (Optional)
#' var_is_active <- "is_active_example" # character |  (Optional)
#' var_order_by <- c("-end_date") # array[character] | Ordenamiento   (Optional)
#' var_page <- 56 # integer | Un número de página dentro del conjunto de resultados paginado. (Optional)
#' var_page_size <- 56 # integer | Número de resultados a devolver por página. (Optional)
#'
#' api_instance <- mosquitoalert_api$new()
#'
#' # Configure API key authorization: tokenAuth
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#' # Configure API key authorization: cookieAuth
#' api_instance$api_client$api_keys["sessionid"] <- Sys.getenv("API_KEY")
#'
#' # Configure HTTP bearer authorization: jwtAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$list(country_id = var_country_id, is_active = var_is_active, order_by = var_order_by, page = var_page, page_size = var_page_sizedata_file = "result.txt")
#' result <- api_instance$campaigns_api$list(country_id = var_country_id, is_active = var_is_active, order_by = var_order_by, page = var_page, page_size = var_page_size)
#' dput(result)
#'
#'
#' ####################  retrieve  ####################
#'
#' library(MosquitoAlert)
#' var_id <- 56 # integer | Un valor de entero único que identifique este ow campaigns.
#'
#' api_instance <- mosquitoalert_api$new()
#'
#' # Configure API key authorization: tokenAuth
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#' # Configure API key authorization: cookieAuth
#' api_instance$api_client$api_keys["sessionid"] <- Sys.getenv("API_KEY")
#'
#' # Configure HTTP bearer authorization: jwtAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$retrieve(var_iddata_file = "result.txt")
#' result <- api_instance$campaigns_api$retrieve(var_id)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
CampaignsApi <- R6::R6Class(
  "CampaignsApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new CampaignsApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' 
    #'
    #' @param country_id (optional) Country in which the campaign is taking place
    #' @param is_active (optional) No description
    #' @param order_by (optional) Ordenamiento  
    #' @param page (optional) Un número de página dentro del conjunto de resultados paginado.
    #' @param page_size (optional) Número de resultados a devolver por página.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return PaginatedCampaignList
    list = function(country_id = NULL, is_active = NULL, order_by = NULL, page = NULL, page_size = NULL, data_file = NULL, ...) {
      local_var_response <- self$list_with_http_info(country_id, is_active, order_by, page, page_size, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param country_id (optional) Country in which the campaign is taking place
    #' @param is_active (optional) No description
    #' @param order_by (optional) Ordenamiento  
    #' @param page (optional) Un número de página dentro del conjunto de resultados paginado.
    #' @param page_size (optional) Número de resultados a devolver por página.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (PaginatedCampaignList) with additional information such as HTTP status code, headers
    list_with_http_info = function(country_id = NULL, is_active = NULL, order_by = NULL, page = NULL, page_size = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (!missing(`country_id`) && is.null(`country_id`)) {
        stop("Invalid value for `country_id` when calling CampaignsApi$list, `country_id` is not nullable")
      }

      if (!missing(`is_active`) && is.null(`is_active`)) {
        stop("Invalid value for `is_active` when calling CampaignsApi$list, `is_active` is not nullable")
      }

      if (!missing(`order_by`) && is.null(`order_by`)) {
        stop("Invalid value for `order_by` when calling CampaignsApi$list, `order_by` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling CampaignsApi$list, `page` is not nullable")
      }

      if (!missing(`page_size`) && is.null(`page_size`)) {
        stop("Invalid value for `page_size` when calling CampaignsApi$list, `page_size` is not nullable")
      }

      query_params[["country_id"]] <- `country_id`

      query_params[["is_active"]] <- `is_active`

      # no explore
      # validate enum values
      for (query_item in `order_by`) {
        if (!is.null(query_item) && !(query_item %in% c("-end_date", "-start_date", "end_date", "start_date"))) {
          stop("Invalid value for order_by when calling CampaignsApi$list. Must be [-end_date, -start_date, end_date, start_date].")
        }
      }
      query_params[["order_by"]] <- I(paste(lapply(`order_by`, URLencode, reserved = TRUE), collapse = ","))

      query_params[["page"]] <- `page`

      query_params[["page_size"]] <- `page_size`

      local_var_url_path <- "/campaigns/"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }
      # API key authentication
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "PaginatedCampaignList"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' 
    #'
    #' @param id Un valor de entero único que identifique este ow campaigns.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return Campaign
    retrieve = function(id, data_file = NULL, ...) {
      local_var_response <- self$retrieve_with_http_info(id, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param id Un valor de entero único que identifique este ow campaigns.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (Campaign) with additional information such as HTTP status code, headers
    retrieve_with_http_info = function(id, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (!missing(`id`) && is.null(`id`)) {
        stop("Invalid value for `id` when calling CampaignsApi$retrieve, `id` is not nullable")
      }

      local_var_url_path <- "/campaigns/{id}/"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }
      # API key authentication
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "Campaign"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
