#' Mosquito Alert API
#'
#' Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
#'
#' The version of the OpenAPI document: v1
#' Contact: it@mosquitoalert.com
#' Generated by: https://openapi-generator.tech
#'
#' MosquitoAlert API Class
#'
#' A single point of access to the MosquitoAlert API.
#'
#' NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
#' Ref: https://openapi-generator.tech
#' Do not edit the class manually.
#'
#' @docType class
#' @title ApiClient
#' @description ApiClient Class
#' @format An \code{R6Class} generator object
#' @field api_client API client
#' @field auth_api an instance of AuthApi
#' @field bites_api an instance of BitesApi
#' @field breeding_sites_api an instance of BreedingSitesApi
#' @field campaigns_api an instance of CampaignsApi
#' @field countries_api an instance of CountriesApi
#' @field devices_api an instance of DevicesApi
#' @field fixes_api an instance of FixesApi
#' @field identification_tasks_api an instance of IdentificationTasksApi
#' @field notifications_api an instance of NotificationsApi
#' @field observations_api an instance of ObservationsApi
#' @field partners_api an instance of PartnersApi
#' @field permissions_api an instance of PermissionsApi
#' @field photos_api an instance of PhotosApi
#' @field status_api an instance of StatusApi
#' @field taxa_api an instance of TaxaApi
#' @field users_api an instance of UsersApi
#' @export
mosquitoalert_api <- R6::R6Class(
  "mosquitoalert_api",
  public = list(
    api_client = NULL,
    auth_api = NULL,
    bites_api = NULL,
    breeding_sites_api = NULL,
    campaigns_api = NULL,
    countries_api = NULL,
    devices_api = NULL,
    fixes_api = NULL,
    identification_tasks_api = NULL,
    notifications_api = NULL,
    observations_api = NULL,
    partners_api = NULL,
    permissions_api = NULL,
    photos_api = NULL,
    status_api = NULL,
    taxa_api = NULL,
    users_api = NULL,
    #' Initialize a new MosquitoAlert API Class.
    #'
    #' @description
    #' Initialize a new MosquitoAlert API Class.
    #'
    #' @param api_client An instance of API client (optional).
    #' @export
    initialize = function(api_client) {
      if (missing(api_client)) {
        self$api_client <- ApiClient$new()
      } else {
        self$api_client <- api_client
      } 

      self$auth_api <- AuthApi$new(self$api_client)

      self$bites_api <- BitesApi$new(self$api_client)

      self$breeding_sites_api <- BreedingSitesApi$new(self$api_client)

      self$campaigns_api <- CampaignsApi$new(self$api_client)

      self$countries_api <- CountriesApi$new(self$api_client)

      self$devices_api <- DevicesApi$new(self$api_client)

      self$fixes_api <- FixesApi$new(self$api_client)

      self$identification_tasks_api <- IdentificationTasksApi$new(self$api_client)

      self$notifications_api <- NotificationsApi$new(self$api_client)

      self$observations_api <- ObservationsApi$new(self$api_client)

      self$partners_api <- PartnersApi$new(self$api_client)

      self$permissions_api <- PermissionsApi$new(self$api_client)

      self$photos_api <- PhotosApi$new(self$api_client)

      self$status_api <- StatusApi$new(self$api_client)

      self$taxa_api <- TaxaApi$new(self$api_client)

      self$users_api <- UsersApi$new(self$api_client)

    }
  )
)
