#' Mosquito Alert API
#'
#' Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
#'
#' The version of the OpenAPI document: v1
#' Contact: it@mosquitoalert.com
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Observations operations
#' @description ObservationsApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  create  ####################
#'
#' library(MosquitoAlert)
#' var_created_at <- "created_at_example" # character | 
#' var_sent_at <- "sent_at_example" # character | 
#' var_location <- LocationRequest$new("auto", Location_point$new(123, 123)) # LocationRequest | 
#' var_photos <- c(SimplePhotoRequest$new(123)) # array[SimplePhotoRequest] | 
#' var_note <- "note_example" # character | Note user attached to report. (Optional)
#' var_tags <- c("inner_example") # array[character] |  (Optional)
#' var_event_environment <- "event_environment_example" # character | The environment where the event took place. (Optional)
#' var_event_moment <- "event_moment_example" # character | The moment of the day when the event took place. (Optional)
#' var_mosquito_appearance <- MosquitoAppearanceRequest$new("albopictus", "albopictus", "albopictus", "albopictus") # MosquitoAppearanceRequest | User-provided description of the mosquito's appearance (Optional)
#'
#' api_instance <- mosquitoalert_api$new()
#'
#' # Configure API key authorization: tokenAuth
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#' # Configure API key authorization: cookieAuth
#' api_instance$api_client$api_keys["sessionid"] <- Sys.getenv("API_KEY")
#'
#' # Configure HTTP bearer authorization: jwtAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$create(var_created_at, var_sent_at, var_location, var_photos, note = var_note, tags = var_tags, event_environment = var_event_environment, event_moment = var_event_moment, mosquito_appearance = var_mosquito_appearancedata_file = "result.txt")
#' result <- api_instance$observations_api$create(var_created_at, var_sent_at, var_location, var_photos, note = var_note, tags = var_tags, event_environment = var_event_environment, event_moment = var_event_moment, mosquito_appearance = var_mosquito_appearance)
#' dput(result)
#'
#'
#' ####################  destroy  ####################
#'
#' library(MosquitoAlert)
#' var_uuid <- "uuid_example" # character | 
#'
#' api_instance <- mosquitoalert_api$new()
#'
#' # Configure API key authorization: tokenAuth
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#' # Configure API key authorization: cookieAuth
#' api_instance$api_client$api_keys["sessionid"] <- Sys.getenv("API_KEY")
#'
#' # Configure HTTP bearer authorization: jwtAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$observations_api$destroy(var_uuid)
#'
#'
#' ####################  list  ####################
#'
#' library(MosquitoAlert)
#' var_country_id <- 56 # integer |  (Optional)
#' var_created_at_after <- "created_at_after_example" # character | Created at (Optional)
#' var_created_at_before <- "created_at_before_example" # character | Created at (Optional)
#' var_has_photos <- "has_photos_example" # character | Has any photo (Optional)
#' var_identification_taxon_ids <- c(123) # array[integer] |  (Optional)
#' var_order_by <- c("-created_at") # array[character] | Ordenado   (Optional)
#' var_page <- 56 # integer | A page number within the paginated result set. (Optional)
#' var_page_size <- 56 # integer | Number of results to return per page. (Optional)
#' var_received_at_after <- "received_at_after_example" # character | Received at (Optional)
#' var_received_at_before <- "received_at_before_example" # character | Received at (Optional)
#' var_search <- "search_example" # character | A search term. (Optional)
#' var_short_id <- "short_id_example" # character | Short ID (Optional)
#' var_updated_at_after <- "updated_at_after_example" # character | Update at (Optional)
#' var_updated_at_before <- "updated_at_before_example" # character | Update at (Optional)
#' var_user_uuid <- "user_uuid_example" # character |  (Optional)
#'
#' api_instance <- mosquitoalert_api$new()
#'
#' # Configure API key authorization: tokenAuth
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#' # Configure API key authorization: cookieAuth
#' api_instance$api_client$api_keys["sessionid"] <- Sys.getenv("API_KEY")
#'
#' # Configure HTTP bearer authorization: jwtAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$list(country_id = var_country_id, created_at_after = var_created_at_after, created_at_before = var_created_at_before, has_photos = var_has_photos, identification_taxon_ids = var_identification_taxon_ids, order_by = var_order_by, page = var_page, page_size = var_page_size, received_at_after = var_received_at_after, received_at_before = var_received_at_before, search = var_search, short_id = var_short_id, updated_at_after = var_updated_at_after, updated_at_before = var_updated_at_before, user_uuid = var_user_uuiddata_file = "result.txt")
#' result <- api_instance$observations_api$list(country_id = var_country_id, created_at_after = var_created_at_after, created_at_before = var_created_at_before, has_photos = var_has_photos, identification_taxon_ids = var_identification_taxon_ids, order_by = var_order_by, page = var_page, page_size = var_page_size, received_at_after = var_received_at_after, received_at_before = var_received_at_before, search = var_search, short_id = var_short_id, updated_at_after = var_updated_at_after, updated_at_before = var_updated_at_before, user_uuid = var_user_uuid)
#' dput(result)
#'
#'
#' ####################  list_mine  ####################
#'
#' library(MosquitoAlert)
#' var_country_id <- 56 # integer |  (Optional)
#' var_created_at_after <- "created_at_after_example" # character | Created at (Optional)
#' var_created_at_before <- "created_at_before_example" # character | Created at (Optional)
#' var_has_photos <- "has_photos_example" # character | Has any photo (Optional)
#' var_identification_taxon_ids <- c(123) # array[integer] |  (Optional)
#' var_order_by <- c("-created_at") # array[character] | Ordenado   (Optional)
#' var_page <- 56 # integer | A page number within the paginated result set. (Optional)
#' var_page_size <- 56 # integer | Number of results to return per page. (Optional)
#' var_received_at_after <- "received_at_after_example" # character | Received at (Optional)
#' var_received_at_before <- "received_at_before_example" # character | Received at (Optional)
#' var_search <- "search_example" # character | A search term. (Optional)
#' var_short_id <- "short_id_example" # character | Short ID (Optional)
#' var_updated_at_after <- "updated_at_after_example" # character | Update at (Optional)
#' var_updated_at_before <- "updated_at_before_example" # character | Update at (Optional)
#' var_user_uuid <- "user_uuid_example" # character |  (Optional)
#'
#' api_instance <- mosquitoalert_api$new()
#'
#' # Configure API key authorization: tokenAuth
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#' # Configure API key authorization: cookieAuth
#' api_instance$api_client$api_keys["sessionid"] <- Sys.getenv("API_KEY")
#'
#' # Configure HTTP bearer authorization: jwtAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$list_mine(country_id = var_country_id, created_at_after = var_created_at_after, created_at_before = var_created_at_before, has_photos = var_has_photos, identification_taxon_ids = var_identification_taxon_ids, order_by = var_order_by, page = var_page, page_size = var_page_size, received_at_after = var_received_at_after, received_at_before = var_received_at_before, search = var_search, short_id = var_short_id, updated_at_after = var_updated_at_after, updated_at_before = var_updated_at_before, user_uuid = var_user_uuiddata_file = "result.txt")
#' result <- api_instance$observations_api$list_mine(country_id = var_country_id, created_at_after = var_created_at_after, created_at_before = var_created_at_before, has_photos = var_has_photos, identification_taxon_ids = var_identification_taxon_ids, order_by = var_order_by, page = var_page, page_size = var_page_size, received_at_after = var_received_at_after, received_at_before = var_received_at_before, search = var_search, short_id = var_short_id, updated_at_after = var_updated_at_after, updated_at_before = var_updated_at_before, user_uuid = var_user_uuid)
#' dput(result)
#'
#'
#' ####################  retrieve  ####################
#'
#' library(MosquitoAlert)
#' var_uuid <- "uuid_example" # character | 
#'
#' api_instance <- mosquitoalert_api$new()
#'
#' # Configure API key authorization: tokenAuth
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#' # Configure API key authorization: cookieAuth
#' api_instance$api_client$api_keys["sessionid"] <- Sys.getenv("API_KEY")
#'
#' # Configure HTTP bearer authorization: jwtAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$retrieve(var_uuiddata_file = "result.txt")
#' result <- api_instance$observations_api$retrieve(var_uuid)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
ObservationsApi <- R6::R6Class(
  "ObservationsApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new ObservationsApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' 
    #'
    #' @param created_at 
    #' @param sent_at 
    #' @param location 
    #' @param photos 
    #' @param note (optional) Note user attached to report.
    #' @param tags (optional) No description
    #' @param event_environment (optional) The environment where the event took place.
    #' @param event_moment (optional) The moment of the day when the event took place.
    #' @param mosquito_appearance (optional) User-provided description of the mosquito's appearance
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return Observation
    create = function(created_at, sent_at, location, photos, note = NULL, tags = NULL, event_environment = NULL, event_moment = NULL, mosquito_appearance = NULL, data_file = NULL, ...) {
      local_var_response <- self$create_with_http_info(created_at, sent_at, location, photos, note, tags, event_environment, event_moment, mosquito_appearance, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param created_at 
    #' @param sent_at 
    #' @param location 
    #' @param photos 
    #' @param note (optional) Note user attached to report.
    #' @param tags (optional) No description
    #' @param event_environment (optional) The environment where the event took place.
    #' @param event_moment (optional) The moment of the day when the event took place.
    #' @param mosquito_appearance (optional) User-provided description of the mosquito's appearance
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (Observation) with additional information such as HTTP status code, headers
    create_with_http_info = function(created_at, sent_at, location, photos, note = NULL, tags = NULL, event_environment = NULL, event_moment = NULL, mosquito_appearance = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`created_at`)) {
        stop("Missing required parameter `created_at`.")
      }

      if (missing(`sent_at`)) {
        stop("Missing required parameter `sent_at`.")
      }

      if (missing(`location`)) {
        stop("Missing required parameter `location`.")
      }

      if (missing(`photos`)) {
        stop("Missing required parameter `photos`.")
      }

      if (!missing(`created_at`) && is.null(`created_at`)) {
        stop("Invalid value for `created_at` when calling ObservationsApi$create, `created_at` is not nullable")
      }

      if (!missing(`sent_at`) && is.null(`sent_at`)) {
        stop("Invalid value for `sent_at` when calling ObservationsApi$create, `sent_at` is not nullable")
      }

      if (!missing(`location`) && is.null(`location`)) {
        stop("Invalid value for `location` when calling ObservationsApi$create, `location` is not nullable")
      }

      if (!missing(`photos`) && is.null(`photos`)) {
        stop("Invalid value for `photos` when calling ObservationsApi$create, `photos` is not nullable")
      }


      if (!missing(`tags`) && is.null(`tags`)) {
        stop("Invalid value for `tags` when calling ObservationsApi$create, `tags` is not nullable")
      }




      form_params["created_at"] <- `created_at`
      form_params["sent_at"] <- `sent_at`
      form_params["location"] <- `location`
      form_params["note"] <- `note`
      form_params["tags"] <- `tags`
      form_params["photos"] <- `photos`
      form_params["event_environment"] <- `event_environment`
      form_params["event_moment"] <- `event_moment`
      form_params["mosquito_appearance"] <- `mosquito_appearance`
      local_var_url_path <- "/observations/"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }
      # API key authentication
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("multipart/form-data", "application/x-www-form-urlencoded")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "Observation"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' 
    #'
    #' @param uuid 
    #' @param ... Other optional arguments
    #'
    #' @return void
    destroy = function(uuid, ...) {
      local_var_response <- self$destroy_with_http_info(uuid, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param uuid 
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    destroy_with_http_info = function(uuid, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`uuid`)) {
        stop("Missing required parameter `uuid`.")
      }

      if (!missing(`uuid`) && is.null(`uuid`)) {
        stop("Invalid value for `uuid` when calling ObservationsApi$destroy, `uuid` is not nullable")
      }

      local_var_url_path <- "/observations/{uuid}/"
      if (!missing(`uuid`)) {
        local_var_url_path <- gsub("\\{uuid\\}", URLencode(as.character(`uuid`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }
      # API key authentication
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "DELETE",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' 
    #'
    #' @param country_id (optional) No description
    #' @param created_at_after (optional) Created at
    #' @param created_at_before (optional) Created at
    #' @param has_photos (optional) Has any photo
    #' @param identification_taxon_ids (optional) No description
    #' @param order_by (optional) Ordenado  
    #' @param page (optional) A page number within the paginated result set.
    #' @param page_size (optional) Number of results to return per page.
    #' @param received_at_after (optional) Received at
    #' @param received_at_before (optional) Received at
    #' @param search (optional) A search term.
    #' @param short_id (optional) Short ID
    #' @param updated_at_after (optional) Update at
    #' @param updated_at_before (optional) Update at
    #' @param user_uuid (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return PaginatedObservationList
    list = function(country_id = NULL, created_at_after = NULL, created_at_before = NULL, has_photos = NULL, identification_taxon_ids = NULL, order_by = NULL, page = NULL, page_size = NULL, received_at_after = NULL, received_at_before = NULL, search = NULL, short_id = NULL, updated_at_after = NULL, updated_at_before = NULL, user_uuid = NULL, data_file = NULL, ...) {
      local_var_response <- self$list_with_http_info(country_id, created_at_after, created_at_before, has_photos, identification_taxon_ids, order_by, page, page_size, received_at_after, received_at_before, search, short_id, updated_at_after, updated_at_before, user_uuid, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param country_id (optional) No description
    #' @param created_at_after (optional) Created at
    #' @param created_at_before (optional) Created at
    #' @param has_photos (optional) Has any photo
    #' @param identification_taxon_ids (optional) No description
    #' @param order_by (optional) Ordenado  
    #' @param page (optional) A page number within the paginated result set.
    #' @param page_size (optional) Number of results to return per page.
    #' @param received_at_after (optional) Received at
    #' @param received_at_before (optional) Received at
    #' @param search (optional) A search term.
    #' @param short_id (optional) Short ID
    #' @param updated_at_after (optional) Update at
    #' @param updated_at_before (optional) Update at
    #' @param user_uuid (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (PaginatedObservationList) with additional information such as HTTP status code, headers
    list_with_http_info = function(country_id = NULL, created_at_after = NULL, created_at_before = NULL, has_photos = NULL, identification_taxon_ids = NULL, order_by = NULL, page = NULL, page_size = NULL, received_at_after = NULL, received_at_before = NULL, search = NULL, short_id = NULL, updated_at_after = NULL, updated_at_before = NULL, user_uuid = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE


      if (!missing(`created_at_after`) && is.null(`created_at_after`)) {
        stop("Invalid value for `created_at_after` when calling ObservationsApi$list, `created_at_after` is not nullable")
      }

      if (!missing(`created_at_before`) && is.null(`created_at_before`)) {
        stop("Invalid value for `created_at_before` when calling ObservationsApi$list, `created_at_before` is not nullable")
      }

      if (!missing(`has_photos`) && is.null(`has_photos`)) {
        stop("Invalid value for `has_photos` when calling ObservationsApi$list, `has_photos` is not nullable")
      }

      if (!missing(`identification_taxon_ids`) && is.null(`identification_taxon_ids`)) {
        stop("Invalid value for `identification_taxon_ids` when calling ObservationsApi$list, `identification_taxon_ids` is not nullable")
      }

      if (!missing(`order_by`) && is.null(`order_by`)) {
        stop("Invalid value for `order_by` when calling ObservationsApi$list, `order_by` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling ObservationsApi$list, `page` is not nullable")
      }

      if (!missing(`page_size`) && is.null(`page_size`)) {
        stop("Invalid value for `page_size` when calling ObservationsApi$list, `page_size` is not nullable")
      }

      if (!missing(`received_at_after`) && is.null(`received_at_after`)) {
        stop("Invalid value for `received_at_after` when calling ObservationsApi$list, `received_at_after` is not nullable")
      }

      if (!missing(`received_at_before`) && is.null(`received_at_before`)) {
        stop("Invalid value for `received_at_before` when calling ObservationsApi$list, `received_at_before` is not nullable")
      }

      if (!missing(`search`) && is.null(`search`)) {
        stop("Invalid value for `search` when calling ObservationsApi$list, `search` is not nullable")
      }

      if (!missing(`short_id`) && is.null(`short_id`)) {
        stop("Invalid value for `short_id` when calling ObservationsApi$list, `short_id` is not nullable")
      }

      if (!missing(`updated_at_after`) && is.null(`updated_at_after`)) {
        stop("Invalid value for `updated_at_after` when calling ObservationsApi$list, `updated_at_after` is not nullable")
      }

      if (!missing(`updated_at_before`) && is.null(`updated_at_before`)) {
        stop("Invalid value for `updated_at_before` when calling ObservationsApi$list, `updated_at_before` is not nullable")
      }

      if (!missing(`user_uuid`) && is.null(`user_uuid`)) {
        stop("Invalid value for `user_uuid` when calling ObservationsApi$list, `user_uuid` is not nullable")
      }

      query_params[["country_id"]] <- `country_id`

      query_params[["created_at_after"]] <- `created_at_after`

      query_params[["created_at_before"]] <- `created_at_before`

      query_params[["has_photos"]] <- `has_photos`

      # explore
      for (query_item in `identification_taxon_ids`) {
        query_params[["identification_taxon_ids"]] <- c(query_params[["identification_taxon_ids"]], list(`identification_taxon_ids` = query_item))
      }

      # no explore
      # validate enum values
      for (query_item in `order_by`) {
        if (!is.null(query_item) && !(query_item %in% c("-created_at", "-received_at", "created_at", "received_at"))) {
          stop("Invalid value for order_by when calling ObservationsApi$list. Must be [-created_at, -received_at, created_at, received_at].")
        }
      }
      query_params[["order_by"]] <- I(paste(lapply(`order_by`, URLencode, reserved = TRUE), collapse = ","))

      query_params[["page"]] <- `page`

      query_params[["page_size"]] <- `page_size`

      query_params[["received_at_after"]] <- `received_at_after`

      query_params[["received_at_before"]] <- `received_at_before`

      query_params[["search"]] <- `search`

      query_params[["short_id"]] <- `short_id`

      query_params[["updated_at_after"]] <- `updated_at_after`

      query_params[["updated_at_before"]] <- `updated_at_before`

      query_params[["user_uuid"]] <- `user_uuid`

      local_var_url_path <- "/observations/"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }
      # API key authentication
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "PaginatedObservationList"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' 
    #'
    #' @param country_id (optional) No description
    #' @param created_at_after (optional) Created at
    #' @param created_at_before (optional) Created at
    #' @param has_photos (optional) Has any photo
    #' @param identification_taxon_ids (optional) No description
    #' @param order_by (optional) Ordenado  
    #' @param page (optional) A page number within the paginated result set.
    #' @param page_size (optional) Number of results to return per page.
    #' @param received_at_after (optional) Received at
    #' @param received_at_before (optional) Received at
    #' @param search (optional) A search term.
    #' @param short_id (optional) Short ID
    #' @param updated_at_after (optional) Update at
    #' @param updated_at_before (optional) Update at
    #' @param user_uuid (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return PaginatedObservationList
    list_mine = function(country_id = NULL, created_at_after = NULL, created_at_before = NULL, has_photos = NULL, identification_taxon_ids = NULL, order_by = NULL, page = NULL, page_size = NULL, received_at_after = NULL, received_at_before = NULL, search = NULL, short_id = NULL, updated_at_after = NULL, updated_at_before = NULL, user_uuid = NULL, data_file = NULL, ...) {
      local_var_response <- self$list_mine_with_http_info(country_id, created_at_after, created_at_before, has_photos, identification_taxon_ids, order_by, page, page_size, received_at_after, received_at_before, search, short_id, updated_at_after, updated_at_before, user_uuid, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param country_id (optional) No description
    #' @param created_at_after (optional) Created at
    #' @param created_at_before (optional) Created at
    #' @param has_photos (optional) Has any photo
    #' @param identification_taxon_ids (optional) No description
    #' @param order_by (optional) Ordenado  
    #' @param page (optional) A page number within the paginated result set.
    #' @param page_size (optional) Number of results to return per page.
    #' @param received_at_after (optional) Received at
    #' @param received_at_before (optional) Received at
    #' @param search (optional) A search term.
    #' @param short_id (optional) Short ID
    #' @param updated_at_after (optional) Update at
    #' @param updated_at_before (optional) Update at
    #' @param user_uuid (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (PaginatedObservationList) with additional information such as HTTP status code, headers
    list_mine_with_http_info = function(country_id = NULL, created_at_after = NULL, created_at_before = NULL, has_photos = NULL, identification_taxon_ids = NULL, order_by = NULL, page = NULL, page_size = NULL, received_at_after = NULL, received_at_before = NULL, search = NULL, short_id = NULL, updated_at_after = NULL, updated_at_before = NULL, user_uuid = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE


      if (!missing(`created_at_after`) && is.null(`created_at_after`)) {
        stop("Invalid value for `created_at_after` when calling ObservationsApi$list_mine, `created_at_after` is not nullable")
      }

      if (!missing(`created_at_before`) && is.null(`created_at_before`)) {
        stop("Invalid value for `created_at_before` when calling ObservationsApi$list_mine, `created_at_before` is not nullable")
      }

      if (!missing(`has_photos`) && is.null(`has_photos`)) {
        stop("Invalid value for `has_photos` when calling ObservationsApi$list_mine, `has_photos` is not nullable")
      }

      if (!missing(`identification_taxon_ids`) && is.null(`identification_taxon_ids`)) {
        stop("Invalid value for `identification_taxon_ids` when calling ObservationsApi$list_mine, `identification_taxon_ids` is not nullable")
      }

      if (!missing(`order_by`) && is.null(`order_by`)) {
        stop("Invalid value for `order_by` when calling ObservationsApi$list_mine, `order_by` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling ObservationsApi$list_mine, `page` is not nullable")
      }

      if (!missing(`page_size`) && is.null(`page_size`)) {
        stop("Invalid value for `page_size` when calling ObservationsApi$list_mine, `page_size` is not nullable")
      }

      if (!missing(`received_at_after`) && is.null(`received_at_after`)) {
        stop("Invalid value for `received_at_after` when calling ObservationsApi$list_mine, `received_at_after` is not nullable")
      }

      if (!missing(`received_at_before`) && is.null(`received_at_before`)) {
        stop("Invalid value for `received_at_before` when calling ObservationsApi$list_mine, `received_at_before` is not nullable")
      }

      if (!missing(`search`) && is.null(`search`)) {
        stop("Invalid value for `search` when calling ObservationsApi$list_mine, `search` is not nullable")
      }

      if (!missing(`short_id`) && is.null(`short_id`)) {
        stop("Invalid value for `short_id` when calling ObservationsApi$list_mine, `short_id` is not nullable")
      }

      if (!missing(`updated_at_after`) && is.null(`updated_at_after`)) {
        stop("Invalid value for `updated_at_after` when calling ObservationsApi$list_mine, `updated_at_after` is not nullable")
      }

      if (!missing(`updated_at_before`) && is.null(`updated_at_before`)) {
        stop("Invalid value for `updated_at_before` when calling ObservationsApi$list_mine, `updated_at_before` is not nullable")
      }

      if (!missing(`user_uuid`) && is.null(`user_uuid`)) {
        stop("Invalid value for `user_uuid` when calling ObservationsApi$list_mine, `user_uuid` is not nullable")
      }

      query_params[["country_id"]] <- `country_id`

      query_params[["created_at_after"]] <- `created_at_after`

      query_params[["created_at_before"]] <- `created_at_before`

      query_params[["has_photos"]] <- `has_photos`

      # explore
      for (query_item in `identification_taxon_ids`) {
        query_params[["identification_taxon_ids"]] <- c(query_params[["identification_taxon_ids"]], list(`identification_taxon_ids` = query_item))
      }

      # no explore
      # validate enum values
      for (query_item in `order_by`) {
        if (!is.null(query_item) && !(query_item %in% c("-created_at", "-received_at", "created_at", "received_at"))) {
          stop("Invalid value for order_by when calling ObservationsApi$list_mine. Must be [-created_at, -received_at, created_at, received_at].")
        }
      }
      query_params[["order_by"]] <- I(paste(lapply(`order_by`, URLencode, reserved = TRUE), collapse = ","))

      query_params[["page"]] <- `page`

      query_params[["page_size"]] <- `page_size`

      query_params[["received_at_after"]] <- `received_at_after`

      query_params[["received_at_before"]] <- `received_at_before`

      query_params[["search"]] <- `search`

      query_params[["short_id"]] <- `short_id`

      query_params[["updated_at_after"]] <- `updated_at_after`

      query_params[["updated_at_before"]] <- `updated_at_before`

      query_params[["user_uuid"]] <- `user_uuid`

      local_var_url_path <- "/me/observations/"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }
      # API key authentication
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "PaginatedObservationList"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' 
    #'
    #' @param uuid 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return Observation
    retrieve = function(uuid, data_file = NULL, ...) {
      local_var_response <- self$retrieve_with_http_info(uuid, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param uuid 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (Observation) with additional information such as HTTP status code, headers
    retrieve_with_http_info = function(uuid, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`uuid`)) {
        stop("Missing required parameter `uuid`.")
      }

      if (!missing(`uuid`) && is.null(`uuid`)) {
        stop("Invalid value for `uuid` when calling ObservationsApi$retrieve, `uuid` is not nullable")
      }

      local_var_url_path <- "/observations/{uuid}/"
      if (!missing(`uuid`)) {
        local_var_url_path <- gsub("\\{uuid\\}", URLencode(as.character(`uuid`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }
      # API key authentication
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "Observation"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
