#' Mosquito Alert API
#'
#' Introducing API v1 for Mosquito Alert platform, a project desgined to facilitate citizen science initiatives and enable collaboration among scientists, public health officials, and environmental managers in the investigation and control of disease-carrying mosquitoes.
#'
#' The version of the OpenAPI document: v1
#' Contact: it@mosquitoalert.com
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Stats operations
#' @description StatsApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  list  ####################
#'
#' library(MosquitoAlert)
#' var_area <- "area_example" # character | \"\\<level\\>:\\<id\\>\", e.g. \"country:ES\" or \"nuts2:34\". (Optional)
#' var_cumulative <- "cumulative_example" # character | Whether to return cumulative counts over time. It only applies when grouping by date. Defaults to False. (Optional)
#' var_date_from <- "date_from_example" # character |  (Optional)
#' var_date_to <- "date_to_example" # character |  (Optional)
#' var_group_by <- c("date") # array[character] | Comma-separated subset of: date, type, region. (Optional)
#' var_interval <- "interval_example" # character | The interval at which to aggregate data when grouping by date. Defaults to week. (Optional)
#' var_level <- 56 # integer | The NUTS level to aggregate by when grouping by region. Defaults to NUTS 2. (Optional)
#' var_page <- 56 # integer | A page number within the paginated result set. (Optional)
#' var_page_size <- 56 # integer | Number of results to return per page. (Optional)
#' var_type <- c("bite") # array[character] | Comma-separated subset of: bite, adult, site. (Optional)
#'
#' api_instance <- mosquitoalert_api$new()
#'
#' # Configure API key authorization: tokenAuth
#' api_instance$api_client$api_keys["Authorization"] <- Sys.getenv("API_KEY")
#'
#' # Configure API key authorization: cookieAuth
#' api_instance$api_client$api_keys["sessionid"] <- Sys.getenv("API_KEY")
#'
#' # Configure HTTP bearer authorization: jwtAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$list(area = var_area, cumulative = var_cumulative, date_from = var_date_from, date_to = var_date_to, group_by = var_group_by, interval = var_interval, level = var_level, page = var_page, page_size = var_page_size, type = var_typedata_file = "result.txt")
#' result <- api_instance$stats_api$list(area = var_area, cumulative = var_cumulative, date_from = var_date_from, date_to = var_date_to, group_by = var_group_by, interval = var_interval, level = var_level, page = var_page, page_size = var_page_size, type = var_type)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
StatsApi <- R6::R6Class(
  "StatsApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new StatsApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' 
    #'
    #' @param area (optional) \"\\<level\\>:\\<id\\>\", e.g. \"country:ES\" or \"nuts2:34\".
    #' @param cumulative (optional) Whether to return cumulative counts over time. It only applies when grouping by date. Defaults to False.
    #' @param date_from (optional) No description
    #' @param date_to (optional) No description
    #' @param group_by (optional) Comma-separated subset of: date, type, region.
    #' @param interval (optional) The interval at which to aggregate data when grouping by date. Defaults to week.
    #' @param level (optional) The NUTS level to aggregate by when grouping by region. Defaults to NUTS 2.
    #' @param page (optional) A page number within the paginated result set.
    #' @param page_size (optional) Number of results to return per page.
    #' @param type (optional) Comma-separated subset of: bite, adult, site.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return PaginatedReportStatsResponseList
    list = function(area = NULL, cumulative = NULL, date_from = NULL, date_to = NULL, group_by = NULL, interval = NULL, level = NULL, page = NULL, page_size = NULL, type = NULL, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$list_with_http_info(area, cumulative, date_from, date_to, group_by, interval, level, page, page_size, type, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param area (optional) \"\\<level\\>:\\<id\\>\", e.g. \"country:ES\" or \"nuts2:34\".
    #' @param cumulative (optional) Whether to return cumulative counts over time. It only applies when grouping by date. Defaults to False.
    #' @param date_from (optional) No description
    #' @param date_to (optional) No description
    #' @param group_by (optional) Comma-separated subset of: date, type, region.
    #' @param interval (optional) The interval at which to aggregate data when grouping by date. Defaults to week.
    #' @param level (optional) The NUTS level to aggregate by when grouping by region. Defaults to NUTS 2.
    #' @param page (optional) A page number within the paginated result set.
    #' @param page_size (optional) Number of results to return per page.
    #' @param type (optional) Comma-separated subset of: bite, adult, site.
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (PaginatedReportStatsResponseList) with additional information such as HTTP status code, headers
    list_with_http_info = function(area = NULL, cumulative = NULL, date_from = NULL, date_to = NULL, group_by = NULL, interval = NULL, level = NULL, page = NULL, page_size = NULL, type = NULL, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (!missing(`area`) && is.null(`area`)) {
        stop("Invalid value for `area` when calling StatsApi$list, `area` is not nullable")
      }

      if (!missing(`cumulative`) && is.null(`cumulative`)) {
        stop("Invalid value for `cumulative` when calling StatsApi$list, `cumulative` is not nullable")
      }

      if (!missing(`date_from`) && is.null(`date_from`)) {
        stop("Invalid value for `date_from` when calling StatsApi$list, `date_from` is not nullable")
      }

      if (!missing(`date_to`) && is.null(`date_to`)) {
        stop("Invalid value for `date_to` when calling StatsApi$list, `date_to` is not nullable")
      }

      if (!missing(`group_by`) && is.null(`group_by`)) {
        stop("Invalid value for `group_by` when calling StatsApi$list, `group_by` is not nullable")
      }

      if (!missing(`interval`) && is.null(`interval`)) {
        stop("Invalid value for `interval` when calling StatsApi$list, `interval` is not nullable")
      }

      if (!missing(`level`) && is.null(`level`)) {
        stop("Invalid value for `level` when calling StatsApi$list, `level` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling StatsApi$list, `page` is not nullable")
      }

      if (!missing(`page_size`) && is.null(`page_size`)) {
        stop("Invalid value for `page_size` when calling StatsApi$list, `page_size` is not nullable")
      }

      if (!missing(`type`) && is.null(`type`)) {
        stop("Invalid value for `type` when calling StatsApi$list, `type` is not nullable")
      }

      query_params[["area"]] <- `area`

      query_params[["cumulative"]] <- `cumulative`

      query_params[["date_from"]] <- `date_from`

      query_params[["date_to"]] <- `date_to`

      # no explore
      # validate enum values
      for (query_item in `group_by`) {
        if (!is.null(query_item) && !(query_item %in% c("date", "type", "region"))) {
          stop("Invalid value for group_by when calling StatsApi$list. Must be [date, type, region].")
        }
      }
      query_params[["group_by"]] <- I(paste(lapply(`group_by`, URLencode, reserved = TRUE), collapse = ","))

      if (!is.null(`interval`) && !(`interval` %in% c("day", "month", "week"))) {
        stop("Invalid value for interval when calling StatsApi$list. Must be [day, month, week].")
      }
      query_params[["interval"]] <- `interval`

      if (!is.null(`level`) && !(`level` %in% c("2", "3"))) {
        stop("Invalid value for level when calling StatsApi$list. Must be [2, 3].")
      }
      query_params[["level"]] <- `level`

      query_params[["page"]] <- `page`

      query_params[["page_size"]] <- `page_size`

      # no explore
      # validate enum values
      for (query_item in `type`) {
        if (!is.null(query_item) && !(query_item %in% c("bite", "adult", "site"))) {
          stop("Invalid value for type when calling StatsApi$list. Must be [bite, adult, site].")
        }
      }
      query_params[["type"]] <- I(paste(lapply(`type`, URLencode, reserved = TRUE), collapse = ","))

      local_var_url_path <- "/stats/"
      # API key authentication
      if ("Authorization" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["Authorization"]) > 0) {
        header_params["Authorization"] <- paste(unlist(self$api_client$api_keys["Authorization"]), collapse = "")
      }
      # API key authentication
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "PaginatedReportStatsResponseList"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
